name: petit_httpd
description: A simple HTTP file server integrated with Let's Encrypt, gzip and CORS.
version: 1.0.5
homepage: https://github.com/gmpassos/petit_httpd

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  petit_httpd:


dependencies:
  args_simple: ^1.0.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  shelf_gzip: ^4.0.0
  shelf_letsencrypt: ^1.0.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dependency_validator: ^3.1.2
  coverage: ^1.0.3
  pubspec: ^2.0.1
  path: ^1.8.1
  mercury_client: ^2.1.5

